version: '3.7'

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0
  YARN_CACHE_FOLDER: /.yarn-cache

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.17-alpine
  working_dir: /most-popular
  restart: always
  volumes:
    - .:/most-popular:cached
    - ./node_modules:/most-popular/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  mongodb:
    tty: true
    image: mongo:5.0
    volumes:
      - mongodb:/data/db
    ports:
      - "37930:27017"

  api:
    <<: *node
    working_dir: /most-popular/api
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      MONGO_URL: ${MONGO_URL-mongodb://mongodb:27017}
    depends_on:
      - mongodb
    ports:
      - "37934:37934"

volumes:
  yarn-cache: {}
  mongodb: {}
